# docker-compose.yml
version: '3.8'

services:
  # PHPアプリケーション
  app:
    build: .
    container_name: cooking-cost-app
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - ./logs:/var/www/html/logs
    depends_on:
      - database
    environment:
      - DB_HOST=database
      - DB_NAME=cooking_cost_system
      - DB_USER=root
      - DB_PASS=rootpassword
    networks:
      - cooking-network

  # MySQLデータベース
  database:
    image: mysql:8.0
    container_name: cooking-cost-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: cooking_cost_system
      MYSQL_USER: cooking_user
      MYSQL_PASSWORD: cooking_password
    volumes:
      - db_data:/var/lib/mysql
      - ./setup.sql:/docker-entrypoint-initdb.d/setup.sql
    ports:
      - "3306:3306"
    networks:
      - cooking-network

  # phpMyAdmin (データベース管理)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: cooking-cost-phpmyadmin
    depends_on:
      - database
    environment:
      PMA_HOST: database
      PMA_USER: root
      PMA_PASSWORD: rootpassword
    ports:
      - "8080:80"
    networks:
      - cooking-network

volumes:
  db_data:

networks:
  cooking-network:
    driver: bridge